# Generated by Django 5.2.6 on 2025-10-05 08:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscraper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeScrapingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('searching', 'Searching Videos'), ('fetching_transcripts', 'Fetching Transcripts'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('videos_found', models.IntegerField(default=0)),
                ('transcripts_fetched', models.IntegerField(default=0)),
                ('videos_csv_path', models.CharField(blank=True, max_length=500)),
                ('transcripts_csv_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
